[package]
name = "hexerator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gamedebug_core = { git = "https://github.com/crumblingstatue/gamedebug_core.git", version = "0.1.0" }
clap = { version = "3.2.17", features = ["derive"] }
anyhow = "1.0.61"
rfd = "0.10.0"
rand = "0.8.5"
rmp-serde = "1.1.0"
serde = { version = "1.0.143", features = ["derive"] }
# Need git version because 1.1.1 blocks on 2nd listener.accept() on windows
# Need specific rev because latest git version is broken
interprocess = { git = "https://github.com/kotauskas/interprocess.git", default-features = false, rev = "fc5f2a22a05dea8833f1505a41d2b79a449a412b" }
directories = "4.0.1"
recently_used_list = { git = "https://github.com/crumblingstatue/recently_used_list.git" }
memchr = "2.5.0"
glu-sys = "0.1.4"
thiserror = "1.0.32"
either = "1.7.0"
tree_magic_mini = { version = "3.0.3", features = ["tree_magic_db"] }
bytemuck = "1.12.0"
egui_easy_mark_standalone = { git = "https://github.com/crumblingstatue/egui-easymark-standalone.git", version = "0.1.0" }
index_many = "0.6.1"
enum_dispatch = "0.3.8"
memmap2 = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"

# Compile deps with optimizations in dev mode
[profile.dev.package."*"]
opt-level = 2
